FROM golang:1.16-alpine AS builder
# Build executable stage
WORKDIR /src
COPY app .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app -ldflags="-w -s" application.go

# Build final image
FROM alpine:3.13.5
COPY --from=builder /app /
CMD ["./app"]